description: An informal group of riders who love twisty bumpy roads.

hb:
  revision:
    created_at: false # disable created-at because we use post date for the date of the event
  # js_bundle_name: main # the JS bundle name.
  # css_bundle_name: main # the CSS bundle name.
  full_width: false # when true, the layout takes full width globally.
  header:
    brand: GTJ # the brand name, leave it empty to use site's title.
#    logo_bg: '#dddddd' # logo background color, used by logo with transparent background.
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
       facebook: https://www.facebook.com/groups/339744652011427
       signal: https://signal.group/#CjQKIFP9k4ONdQV4_FC7ehTnQQUmUhB-yvlmBL85eVjlFkcGEhCJ6mI4bl6Ctp6mp8BINagG
       rss: true
       github: goattrails
#      # twitter: razonyang
#      mastodon: https://techhub.social/@hbstack
  footer:
    powered_by: true
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
       _color: false # when false, remove the color of social icons.
       facebook: https://www.facebook.com/groups/339744652011427
       signal: https://signal.group/#CjQKIFP9k4ONdQV4_FC7ehTnQQUmUhB-yvlmBL85eVjlFkcGEhCJ6mI4bl6Ctp6mp8BINagG
       rss: true
       github: goattrails
#      twitter: razonyang
#      mastodon: https://techhub.social/@hbstack
  blog:
    list_cols_md: 2
    list_cols_lg: 3
    toc:
      position: end
    social_share_buttons:
      alignment: end
      icons: true
      labels: true
      media:
      - facebook
    sidebar:
      sticky: true # set it to false to not stick the sidebar.
      width: .35 # the width of sidebar.
      position: start # the sidebar position: start (left) or end (right).
      profile:
        # title: Profile title other than site title.
        # description: Profile description other than site description.
        avatar_size: 100
        company: Goat Trail Junkies
        location: SF Bay Area
        socials:
          facebook: https://www.facebook.com/groups/339744652011427
          signal: https://signal.group/#CjQKIFP9k4ONdQV4_FC7ehTnQQUmUhB-yvlmBL85eVjlFkcGEhCJ6mI4bl6Ctp6mp8BINagG
          github: goattrails
          rss: true
#          mastodon: https://techhub.social/@hbstack
      posts:
        recent_count: 5 # the number of recent posts.
        featured_count: 5 # the number of featured posts.
        style: pills # pills, tabs or underline.
        list_style: slide # slide or vertical.
      taxonomies:
        count: true # whether to show the number of posts associated to the item.
        limit: 10 # the maximum number of the item.
        style: pills # pills, tabs or underline.
        separate: false # whether to separate into multiple sections.
        authors:
          disable: false # whether to disable this taxonomy.
          weight: 1 # the weight of this taxonomy, lower gets higher priority.
          count: false # override the global count setting.
          limit: 5 # override the global limit setting.
        categories:
          disable: false
          weight: 3
        series:
          disable: false
          weight: 2
        tags:
          disable: false
          weight: 4
          limit: 20
          title: Popular Regions # override the title.
    paginate: 12 # paginate.
    post_thumbnail_placeholder: GTJ # the text of thumbnail placeholder, default to site title.
    # post_thumbnail: false # whether to show the thumbnails.
    post_date_format: "Mon Jan 2 2006 3:04 PM MST" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      taxonomies: false # remove the taxonomies stat from the homepage.
      featured_posts: 5 # the number of the featured posts, 0 means disabled.
      pinned_posts_position: "list"
      main_sections: # leave it empty to include all regular pages.
        - docs
        - blog
        - news
        - events
    giscus:
      repo: goattrails/hb-goattrails
      repo_id: R_kgDOK9Lc1Q
      category_id: DIC_kwDOK9Lc1c4CcVdv
  docs:
    giscus:
      repo: goattrails/hb-goattrails
      repo_id: R_kgDOK9Lc1Q
      category_id: DIC_kwDOK9Lc1c4CcVdv
    social_share_buttons:
      alignment: center
      media:
        - facebook
  content_panel:
    repo:
      service: github # github or gitlab.
      repo: goattrails/hb-goattrails
      branch: main
#      subpath: exampleSite
  gallery:
    thumbnail_size: "x640"
    paginate: 24
  # google_fonts:
    # families:
      # - name: Lato

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: images/logo.png # use logo as favicon.

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  debug: false
  manifest:
    background_color: '#712cf9'
    theme_color: '#712cf9'
    short_name: 'Goat Trail Junkies'

# see https://hugomods.com/search/configurations/.
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  # shortcut_search: ["/"]

mermaid:
  # replace it with other CDNs or self-hosted URLs.
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
        hb-blog-post-toc-begin:
          cacheable: false
        hb-blog-post-toc-end:
          cacheable: false
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
# we don't use the sidebar
#        hb-blog-sidebar:
#          cacheable: true
#          weight: 4
#    # change the order of sidebar modules.
#    hb-blog-sidebar-taxonomies:
#      hooks:
#        hb-blog-sidebar:
#          weight: 3
#    hb-blog-sidebar-posts:
#      hooks:
#        hb-blog-sidebar:
#          weight: 2

decap_cms:
  _preview_templates:
   - name: hb/blog-post
     collections:
      - blog
      - news
      - events
  _configs:
    # completely new or redefined fields for events only
    # (may recycle standard field names like date & tags)
    events_field_areas:
      fields:
        areas:
          name: tags
          label: "Areas"
          label_singular: "Area"
          default:
            - "north-bay"
            - "south-bay"
            - "east-bay"
            - "sierras"
            - "norcal"
            - "socal"
            - "mexico"
            - "pnw"
          i18n: true
          required: false
          widget: strings
    events_field_categories:
      fields:
        categories:
          name: categories
          label: "Categories"
          label_singular: "Category"
          default:
            - "rides"
          i18n: true
          required: false
          widget: strings
    events_field_date:
      fields:
        date:
          i18n: true
          name: date
          label: "Event Start Date"
          widget: datetime
          format: "YYYY-MM-DDTHH:mm:ssZZ"
          picker_utc: false
    events_field_end_date:
      fields:
        end_date:
          i18n: true
          name: endDate
          label: "Event Ending Date"
          widget: datetime
          format: "YYYY-MM-DDTHH:mm:ssZZ"
          picker_utc: false
    # we need this since we are recycling date: to be the date of the event, not the date of the posting
    # otherwise the posting wouldn't show up until after the event started!
    events_field_publish_date:
      fields:
        publish_date:
          i18n: true
          name: publishDate
          label: "Post Publish Date"
          widget: datetime
          format: "YYYY-MM-DDTHH:mm:ssZZ"
          picker_utc: false
    events_field_gpxfile:
      fields:
        gpxfile:
          i18n: false
          name: gpxFile
          label: "GPX file"
          hint: "GPX file of route"
          required: false
          widget: file
          summary: "{{fields.gpxFile}}"
          collapsed: true
          minimize_collapsed: true
    events_field_location:
      fields:
        location:
          i18n: false
          name: location
          label: "Start location"
          hint: "Name and address of start location"
          widget: object
          required: false
          summary: "{{fields.title}}{{fields.title | ternary(': ', '')}}{{fields.address}}"
          collapsed: true
          minimize_collapsed: true
          fields:
            - label: Title
              name: title
              widget: string
              required: false
            - label: Address
              name: address
              widget: text
              required: false
    # modifications to default standard entries
    field_authors:
      fields:
        authors:
          default:
            - ich
            - paul
    field_description:
      fields:
        description:
          required: false
    field_draft:
      fields:
        draft:
          default: false
    # hb_comments is not documented particularly well
    hb_field_comments:
      fields:
        comments:
          i18n: false
          name: comments
          label: "Allow comments"
          widget: boolean
          default: true
          required: false
    hb_field_featured:
      fields:
        featured:
          label: "Feature post in carousel"
    hb_field_pinned:
      fields:
        pinned:
          label: "Pin post on front page and carousel"
    events_posts:
      name: events
      label: Events
      label_singular: Event
      create: true
      path: "{{year}}-{{slug}}/index"
      summary: "{{date | truncate(10, ' ')}}{{date | ternary('- ','')}}{{title}}"
      sortable_fields: ["date", "title"]
      view_groups:
        - label: Year
          field: date
          pattern: "\\d{4}"
        - label: Drafts
          field: draft
      _extends:
        - field_title
        - field_draft
        - hb_field_comments
        - hb_field_featured
        - hb_field_pinned
        - events_field_publish_date
        - events_field_date
        - events_field_end_date
        - field_description
        - events_field_location
        - events_field_gpxfile
        - field_images
        - field_aliases
        - field_authors
        - field_series
        - events_field_categories
        - events_field_areas
        - field_body
  search: true
  slug:
    encoding: ascii
    clean_accents: true
    sanitize_replacement: "_"
  collections:
    events:
      description: Upcoming events
      folder: content/events
      _weight: 1
      _extends:
        - events_posts
        - nested
        - meta_path
      fields:
        - {name: "path", default: "{{path}}", required: false}
    blog:
      folder: content/blog
      path: "{{year}}-{{slug}}/index"
      summary: "{{date | truncate(10, ' ')}}{{date | ternary('- ','')}}{{title}}"
      sortable_fields: ["date", "title"]
      view_groups:
        - label: Year
          field: date
          pattern: "\\d{4}"
        - label: Drafts
          field: draft
      _weight: 2
      _extends:
        - hb_blog_posts
        - nested
        - meta_path
      fields:
        - {name: "path", default: "{{path}}", required: false}
#    archives:
#      folder: content/archives
#      _weight: 3
#      _extends:
#        - hb_blog_archives
