description: An informal group of riders who love twisty bumpy roads.

hb:
  revision:
    created_at: false # disable created-at because we use post date for the date of the event
  # js_bundle_name: main # the JS bundle name.
  # css_bundle_name: main # the CSS bundle name.
  full_width: false # when true, the layout takes full width globally.
  header:
    brand: GTJ # the brand name, leave it empty to use site's title.
#    logo_bg: '#dddddd' # logo background color, used by logo with transparent background.
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
       facebook: https://www.facebook.com/groups/339744652011427
       signal: https://signal.group/#CjQKIFP9k4ONdQV4_FC7ehTnQQUmUhB-yvlmBL85eVjlFkcGEhCJ6mI4bl6Ctp6mp8BINagG
       rss: true
       github: goattrails
#      # twitter: razonyang
#      mastodon: https://techhub.social/@hbstack
  footer:
    powered_by: true
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
       _color: false # when false, remove the color of social icons.
       facebook: https://www.facebook.com/groups/339744652011427
       signal: https://signal.group/#CjQKIFP9k4ONdQV4_FC7ehTnQQUmUhB-yvlmBL85eVjlFkcGEhCJ6mI4bl6Ctp6mp8BINagG
       rss: true
       github: goattrails
#      twitter: razonyang
#      mastodon: https://techhub.social/@hbstack
  blog:
    list_cols_md: 2
    list_cols_lg: 3
    toc:
      position: end
    social_share_buttons:
      alignment: end
      icons: true
      labels: true
      media:
      - facebook
    sidebar:
      sticky: true # set it to false to not stick the sidebar.
      width: .35 # the width of sidebar.
      position: end # the sidebar position: start (left) or end (right).
      profile:
        # title: Profile title other than site title.
        # description: Profile description other than site description.
        avatar_size: 100
        company: Goat Trail Junkies
        location: SF Bay Area
        socials:
          facebook: https://www.facebook.com/groups/339744652011427
          signal: https://signal.group/#CjQKIFP9k4ONdQV4_FC7ehTnQQUmUhB-yvlmBL85eVjlFkcGEhCJ6mI4bl6Ctp6mp8BINagG
          github: goattrails
          rss: true
#          mastodon: https://techhub.social/@hbstack
      posts:
        recent_count: 5 # the number of recent posts.
        featured_count: 5 # the number of featured posts.
        style: pills # pills, tabs or underline.
        list_style: slide # slide or vertical.
      taxonomies:
        count: true # whether to show the number of posts associated to the item.
        limit: 10 # the maximum number of the item.
        style: pills # pills, tabs or underline.
        separate: false # whether to separate into mutliple sections.
        authors:
          disable: true # whether to disable this taxonomy.
          weight: 1 # the weight of this taxonomy, lower gets higher priority.
          count: false # override the global count setting.
          limit: 5 # override the global limit setting.
        categories:
          disable: true
          weight: 3
        series:
          disable: true
          weight: 2
        tags:
          disable: false
          weight: 4
          limit: 20
          title: Popular Regions # override the title.
    paginate: 12 # paginate.
    post_thumbnail_placeholder: GTJ # the text of thumbnail placeholder, default to site title.
    # post_thumbnail: false # whether to show the thumbnails.
    post_date_format: "Mon Jan 2 2006 3:04 PM MST" # see https://gohugo.io/functions/dateformat/#datetime-formatting-layouts.
    home: # homepage settings.
      taxonomies: false # remove the taxonomies stat from the homepage.
      featured_posts: 0 # the number of the featured posts, 0 means disabled.
      pinned_posts_position: "list"
      main_sections: # leave it empty to include all regular pages.
        - docs
        - blog
        - news
        - events
    giscus:
      repo: goattrails/hb-goattrails
      repo_id: R_kgDOK9Lc1Q
      category_id: DIC_kwDOK9Lc1c4CcVdv
  docs:
    giscus:
      repo: goattrails/hb-goattrails
      repo_id: R_kgDOK9Lc1Q
      category_id: DIC_kwDOK9Lc1c4CcVdv
  content_panel:
    repo:
      service: github # github or gitlab.
      repo: goattrails/hb-goattrails
      branch: main
#      subpath: exampleSite
  gallery:
    thumbnail_size: "x640"
    paginate: 24
  # google_fonts:
    # families:
      # - name: Lato

seo:
  favicons: # see https://hugomods.com/en/docs/seo/#favicons-module
    icon: images/logo.png # use logo as favicon.

# PWA settings, see https://hugomods.com/en/docs/pwa/#site-parameters.
pwa:
  debug: false
  manifest:
    background_color: '#712cf9'
    theme_color: '#712cf9'
    short_name: 'Goat Trail Junkies'

# see https://hugomods.com/en/docs/search/#site-parameters
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  # shortcut_search: ["/"]

mermaid:
  # replace it with other CDNs or self-hosted URLs.
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    decap-cms:
      hooks:
        head-end:
          cacheable: false
        body-end:
          cacheable: false
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
        hb-blog-post-toc-end:
          cacheable: false
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
#        hb-blog-sidebar:
#          cacheable: true
#          weight: 4
    # change the order of sidebar modules.
#    hb-blog-sidebar-taxonomies:
#      hooks:
#        hb-blog-sidebar:
#          weight: 3
#    hb-blog-sidebar-posts:
#      hooks:
#        hb-blog-sidebar:
#          weight: 2

decap_cms:
  search: true
  logo_url: images/logo.png
  slug:
    encoding: ascii
    clean_accents: true
    sanitize_replacement: "_"
  collections:
    events:
      name: events
      label: Events
      label_singular: Event
      description: Upcoming events
      folder: content/events
      create: true
      nested:
        depth: 3
      slug: "{{year}}-{{slug}}"
      path: "{{slug}}/index"
      fields:
        - {label: "Title", name: title, widget: string}
        - {label: "Description", name: description, widget: text, required: false,
           hint: "plain text, no markdown or html"}
        - {label: "Authors", label_singular: "Author", name: authors, widget: list, required: false, collapsed: true,
           default: ["ich", "paul"]}
        - {label: "Areas", label_singular: "Area", name: tags, widget: list, collapsed: true,
           default: ["north-bay", "south-bay", "east-bay", "sierras", "norcal", "socal", "mexico"],
           hint: "north-bay, south-bay, east-bay, sierras, norcal, socal, mexico, pnw"}
        - {label: "Event Date", name: date, widget: datetime,
           hint: "Date and Time of Event"}
        - {label: "Event Ending Date", name: endDate, widget: datetime, required: false, default: null,
           hint: "Ending time for Event"}
        - {label: "Post Publish Date", name: publishDate, widget: datetime,
           hint: "Start publishing post on..."}
        - {label: "Post Expiration Date", name: expiryDate, widget: hidden, required: false, default: null,
           hint: "Stop publishing post on...."}
        - {label: "Post Hidden", name: hidden, widget: hidden, default: false, required: false,
           hint: "Hide post from front page"}
        - {label: "Post Featured", name: feature, widget: hidden, default: false, required: false,
           hint: "Feature post on front page"}
        - {label: "Post Pinned", name: pinned, widget: hidden, default: false, required: false,
           hint: "Pin post in carousel"}
        - {label: "Allow comments", name: comments, widget: boolean, default: true, required: false,
           hint: "Allow commenting on this post"}
        - {label: "Featured Images", label_singular: "Featured Image", name: images, widget: list, summary: "{{fields.image}}", required: false, collapsed: true,
           hint: "One featured image, and call it feature<something>.jpg",
           field: {label: "Image", name: image, widget: image, choose_url: true}}
        - {label: "Body", name: body, widget: markdown}
    blog:
      name: blog
      label: Blog
      description: Blog Pieces and News
      folder: content/blog
      create: true
      nested:
        depth: 3
      slug: "{{year}}-{{slug}}"
      path: "{{slug}}/index"
      fields:
        - {label: "Title", name: title, widget: string}
        - {label: "Description", name: description, widget: text, required: false,
           hint: "plain text, no markdown or html"}
        - {label: "Authors", label_singular: "Author", name: authors, widget: list, required: false, collapsed: true,
           default: ["ich", "paul"]}
        - {label: "Tags", label_singular: "Tag", name: tags, widget: list, collapsed: true, required: false}
        - {label: "Date", name: date, widget: datetime,
           hint: "Article Date"}
        - {label: "Post Publish Date", name: publishDate, widget: hidden, required: false, default: null,
           hint: "Start publishing post on..."}
        - {label: "Post Expiration Date", name: expiryDate, widget: hidden, required: false, default: null,
           hint: "Stop publishing post on...."}
        - {label: "Post Hidden", name: hidden, widget: hidden, default: false, required: false,
           hint: "Hide post from front page"}
        - {label: "Post Featured", name: feature, widget: hidden, default: false, required: false,
           hint: "Feature post on front page"}
        - {label: "Post Pinned", name: pinned, widget: hidden, default: false, required: false,
           hint: "Pin post in carousel"}
        - {label: "Allow comments", name: comments, widget: boolean, default: true, required: false,
           hint: "Allow commenting on this post"}
        - {label: "Featured Images", label_singular: "Featured Image", name: images, widget: list, summary: "{{fields.image}}", required: false, collapsed: true,
           hint: "One featured image, and call it feature<something>.jpg",
           field: {label: "Image", name: image, widget: image, choose_url: true}}
        - {label: "Body", name: body, widget: markdown}
