[matt]
Xtitle = "Matt"
description = "Matt 'Gecko'"
weight = 1
[matt.image]
Filename = "attendees/matt_gecko.png"
Alt = "Picture of Matt"
XCaption = "Matt Gecko"

[stuart]
Xtitle = "Stuart"
description = "Uncle Stu"
weight = 2
[stuart.image]
Filename = "attendees/uncle_stu.png"
Alt = "Headshot of Stuart"
XCaption = "Uncle Stu"