[build.environment]
NODE_VERSION = "23"
HUGO_VERSION = "0.140.2"
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
GO_VERSION = "1.23.4"
DART_SASS_VERSION = "1.83.0"

[build]
command = "npm ci && hugo --minify --gc -b $URL"
publish = "public"

[context.deploy-preview]
command = "npm ci && hugo --minify --buildFuture --gc -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "npm ci && hugo --minify --buildFuture --gc -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "@gethinode/netlify-plugin-dartsass"

[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
  skipPatterns = ['https://fonts.gstatic.com', 'https://fonts.googleapis.com']

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"

# multilingual 404 pages, remove it on monolingual sites.
[[redirects]]
  from = "/en/*"
  to = "/en/404.html"
  status = 404

[[redirects]]
  from = "/zh-hans/*"
  to = "/zh-hans/404.html"
  status = 404

# fallback 404 page.
[[redirects]]
  from = "/*"
  to = "/404.html"
  # to = "/en/404.html" # use this instead if defaultContentLanguageInSubdir is enabled.
  status = 404
