pwa:
  caches:
    font:
      strategy: network-first
    image:
      strategy: network-first
    script:
      strategy: network-first
    style:
      strategy: network-first

hugopress:
  modules:
    pwa:
      disable: true

decap_cms:
  backend:
    name: git-gateway
  local_backend: true
