# see https://hugomods.com/en/docs/google-adsense/.
# google_adsense = 'ca-pub-XXXXXXXXXXXXXXXX' # Please make that the Google AdSense module was imported.

decap_cms:
  publish_mode: editorial_workflow
  backend:
    name: git-gateway
    branch: main
    open_authoring: true
