# see https://hugomods.com/en/docs/google-adsense/.
# google_adsense = 'ca-pub-XXXXXXXXXXXXXXXX' # Please make that the Google AdSense module was imported.

decap_cms:
  backend:
    name: github
    repo: goattrails/hb-goattrails
    branch: main
    site_domain: goattrails.pst.org
    open_authoring: true
    squash_merges: true
    base_url: https://wc858xnae1.execute-api.us-east-1.amazonaws.com
    auth_endpoint: /prod/auth
  publish_mode: editorial_workflow
